// Included Files
#include "driverlib.h"
#include "device.h"
#include "board.h"
#include "SFO_V8.h"
#include "cla_cpu_shared.h"
#include "hrpwm_control.h"
#include "phase_triggers.h"

// Defines
#define EPWM_TIMER_TBPRD            100UL

// Globals

uint16_t status;

int MEP_ScaleFactor; // Global variable used by the SFO library
                     // Result can be used for all HRPWM channels
                     // This variable is also copied to HRMSTEP
                     // register by SFO() function.

volatile uint32_t ePWM[] =
    {0, myEPWM1_BASE, myEPWM2_BASE, myEPWM3_BASE};

// CPU -> CLA mailbox (CPU writes, CLA reads)
#pragma DATA_SECTION(cpuToClaMsg, "CpuToCla1MsgRAM")
volatile CpuToClaMsg cpuToClaMsg = {0};

// CLA -> CPU mailbox (CLA writes, CPU reads)
#pragma DATA_SECTION(claToCpuMsg, "Cla1ToCpuMsgRAM")
volatile ClaToCpuMsg claToCpuMsg = {0};

void error(void);

// CPU-side Interrupt Service Routines for CLA End-of-Task
// These are required to satisfy the symbols generated by SysConfig
__interrupt void cla1Isr1(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr2(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr3(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr4(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr5(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr6(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr7(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr8(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }

//
// Main
//
void main(void)
{

    // Initialize device clock and peripherals
    Device_init();

    // Disable pin locks and enable internal pull ups.
    Device_initGPIO();

    // Initialize PIE and clear PIE registers. Disables CPU interrupts.
    Interrupt_initModule();

    // Initialize the PIE vector table with pointers to the shell Interrupt
    // Service Routines (ISR).
    Interrupt_initVectorTable();

    // Initialize the EPWM GPIO Pins and change the XBAR inputs from using GPIO0
    Board_init();
    CLA_forceTasks(myCLA0_BASE, CLA_TASKFLAG_1);

    // Optional safety: ensure SFO loop starts correctly
    status = SFO_INCOMPLETE;

    // Precompute all CLA-applied HRPWM values
    precomputePhaseShiftPeriodsForCLA(EPWM_TIMER_TBPRD);

    // Override SysConfig default software trigger: Task1 runs from EPWM1INT
    CLA_setTriggerSource(CLA_TASK_1, CLA_TRIGGER_EPWM1INT);

    // Calling SFO() updates the HRMSTEP register with calibrated MEP_ScaleFactor.
    // HRMSTEP must be populated with a scale factor value prior to enabling
    // high resolution period control.
    while(status == SFO_INCOMPLETE)
    {
        status = SFO();
        if(status == SFO_ERROR)
        {
            error();   // SFO function returns 2 if an error occurs & # of MEP
        }              // steps/coarse step exceeds maximum of 255.
    }



    // Disable sync(Freeze clock to PWM as well)
    SysCtl_disablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);
    SysCtl_setEPWMClockDivider(SYSCTL_EPWMCLK_DIV_1);

    initHRPWM1(myEPWM1_BASE, EPWM_TIMER_TBPRD);
    initAuxiliaryHRPWM(myEPWM2_BASE, EPWM_TIMER_TBPRD);
    initAuxiliaryHRPWM(myEPWM3_BASE, EPWM_TIMER_TBPRD);

    // Enable sync and clock to PWM
    SysCtl_enablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);

    // Set initial duty cycles for auxiliary PWMs
    setAuxiliaryHRPWMDutyCycle(myEPWM2_BASE, EPWM_TIMER_TBPRD, 20);
    setAuxiliaryHRPWMDutyCycle(myEPWM3_BASE, EPWM_TIMER_TBPRD, 80);

    // Arm external lead/lag commands only after PWM is fully configured.
    configureLagLeadHardwareTriggers();
    cpuToClaMsg.cmd_direction = PHASE_NONE;
    cpuToClaMsg.cmd_cycles = 0U;
    cpuToClaMsg.cmd_seq = 0U;
    claToCpuMsg.state_direction = PHASE_NONE;
    claToCpuMsg.state_cycles_remaining = 0U;
    claToCpuMsg.state_active = 0U;
    claToCpuMsg.cmd_ack_seq = cpuToClaMsg.cmd_seq;
    claToCpuMsg.done_count = 0U;


    // Enable ePWM interrupts
    //Interrupt_enable(INT_EPWM1);
    //Interrupt_enable(INT_EPWM2);
    //Interrupt_enable(INT_EPWM3);
    //Interrupt_enable(INT_EPWM4);

    // Enable Global Interrupt (INTM) and realtime interrupt (DBGM)
    EINT;
    ERTM;

    for(;;)
    {
        //
        // Call the scale factor optimizer lib function SFO()
        // periodically to track for any change due to temp/voltage.
        // This function generates MEP_ScaleFactor by running the
        // MEP calibration module in the HRPWM logic. This scale
        // factor can be used for all HRPWM channels. The SFO()
        // function also updates the HRMSTEP register with the
        // scale factor value.
        //
        status = SFO(); // in background, MEP calibration module
                        // continuously updates MEP_ScaleFactor

        if (status == SFO_ERROR)
        {
            error();   // SFO function returns 2 if an error occurs & #
                    // of MEP steps/coarse step
        }              // exceeds maximum of 255.
     }
}

// error - Halt debugger when called
void error (void)
{
    ESTOP0;         // Stop here and handle error
}

