// Included Files
#include "driverlib.h"
#include "device.h"
#include "board.h"
#include "SFO_V8.h"
#include "cla_cpu_shared.h"

// Defines
#define EPWM_TIMER_TBPRD            100UL

//#define MIN_HRPWM_DUTY_PERCENT      4.0/((float32_t)EPWM_TIMER_TBPRD)*100.0
// HR deadband settings: consolidated value format is (coarse << 7) | fine
#define DB_RED_COARSE_COUNT     5U
#define DB_RED_FINE_COUNT       0U
#define DB_FED_COARSE_COUNT     5U
#define DB_FED_FINE_COUNT       0U

#define DB_RED_HR_COUNT         (((uint32_t)DB_RED_COARSE_COUNT << 7U) | DB_RED_FINE_COUNT)
#define DB_FED_HR_COUNT         (((uint32_t)DB_FED_COARSE_COUNT << 7U) | DB_FED_FINE_COUNT)

// Globals

//float32_t dutyFine = MIN_HRPWM_DUTY_PERCENT;
uint16_t status;

int MEP_ScaleFactor; // Global variable used by the SFO library
                     // Result can be used for all HRPWM channels
                     // This variable is also copied to HRMSTEP
                     // register by SFO() function.

//volatile uint32_t ePWM[] =
//    {0, myEPWM1_BASE, myEPWM2_BASE, myEPWM3_BASE, myEPWM4_BASE};
volatile uint32_t ePWM[] =
    {0, myEPWM1_BASE};

// CPU -> CLA command mailbox (CPU writes, CLA reads)
#pragma DATA_SECTION(cla_cmd_direction, "CpuToCla1MsgRAM")
volatile uint16_t cla_cmd_direction = PHASE_NONE;

#pragma DATA_SECTION(cla_cmd_cycles, "CpuToCla1MsgRAM")
volatile uint16_t cla_cmd_cycles = 0U;

#pragma DATA_SECTION(cla_cmd_seq, "CpuToCla1MsgRAM")
volatile uint16_t cla_cmd_seq = 0U;

// CLA -> CPU status mailbox (CLA writes, CPU reads)
#pragma DATA_SECTION(cla_state_direction, "Cla1ToCpuMsgRAM")
volatile uint16_t cla_state_direction = PHASE_NONE;

#pragma DATA_SECTION(cla_state_cycles_remaining, "Cla1ToCpuMsgRAM")
volatile uint16_t cla_state_cycles_remaining = 0U;

#pragma DATA_SECTION(cla_state_active, "Cla1ToCpuMsgRAM")
volatile uint16_t cla_state_active = 0U;

#pragma DATA_SECTION(cla_cmd_ack_seq, "Cla1ToCpuMsgRAM")
volatile uint16_t cla_cmd_ack_seq = 0U;

#pragma DATA_SECTION(cla_done_count, "Cla1ToCpuMsgRAM")
volatile uint32_t cla_done_count = 0U;

#pragma DATA_SECTION(cla_task1_hits, "Cla1ToCpuMsgRAM")
volatile uint32_t cla_task1_hits = 0U;

#pragma DATA_SECTION(cla_period_hr_normal_q8, "CpuToCla1MsgRAM")
volatile uint32_t cla_period_hr_normal_q8 = 0U;

#pragma DATA_SECTION(cla_period_hr_slow_q8, "CpuToCla1MsgRAM")
volatile uint32_t cla_period_hr_slow_q8 = 0U;

#pragma DATA_SECTION(cla_period_hr_fast_q8, "CpuToCla1MsgRAM")
volatile uint32_t cla_period_hr_fast_q8 = 0U;

#pragma DATA_SECTION(cla_cmpa_hr_normal_q8, "CpuToCla1MsgRAM")
volatile uint32_t cla_cmpa_hr_normal_q8 = 0U;

#pragma DATA_SECTION(cla_cmpa_hr_slow_q8, "CpuToCla1MsgRAM")
volatile uint32_t cla_cmpa_hr_slow_q8 = 0U;

#pragma DATA_SECTION(cla_cmpa_hr_fast_q8, "CpuToCla1MsgRAM")
volatile uint32_t cla_cmpa_hr_fast_q8 = 0U;

#pragma DATA_SECTION(xint1_hits, "Cla1ToCpuMsgRAM")
volatile uint32_t xint1_hits = 0U;

#pragma DATA_SECTION(xint2_hits, "Cla1ToCpuMsgRAM")
volatile uint32_t xint2_hits = 0U;
//
// Function Prototypes
//
void initHRPWM1(uint32_t base, uint32_t period);
void error(void);

static void precomputePhaseShiftPeriodsForCLA(void);
static void configureLagLeadHardwareTriggers(void);
__interrupt void xintLeadIsr(void);
__interrupt void xintLagIsr(void);
static volatile uint16_t lagLeadArmed = 0U;
// CPU-side Interrupt Service Routines for CLA End-of-Task
// These are required because SysConfig has them enabled by default.
// CPU-side Interrupt Service Routines for CLA End-of-Task
// These are required to satisfy the symbols generated by SysConfig
__interrupt void cla1Isr1(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr2(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr3(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr4(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr5(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr6(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr7(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
__interrupt void cla1Isr8(void) { Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP11); }
//__interrupt void epwm1ISR(void);
//__interrupt void epwm2ISR(void);
//__interrupt void epwm3ISR(void);
//__interrupt void epwm4ISR(void);

//
// Main
//
void main(void)
{

    // Initialize device clock and peripherals
    Device_init();

    // Disable pin locks and enable internal pull ups.
    Device_initGPIO();

    // Initialize PIE and clear PIE registers. Disables CPU interrupts.
    Interrupt_initModule();

    // Initialize the PIE vector table with pointers to the shell Interrupt
    // Service Routines (ISR).
    Interrupt_initVectorTable();

    // Initialize the EPWM GPIO Pins and change the XBAR inputs from using GPIO0
    Board_init();
    CLA_forceTasks(myCLA0_BASE, CLA_TASKFLAG_1);

    //CLA_setTriggerSource(CLA_TASK_1, CLA_TRIGGER_SOFTWARE);
    //CLA_forceTasks(myCLA0_BASE, CLA_TASKFLAG_1);

    // Optional safety: ensure SFO loop starts correctly
    status = SFO_INCOMPLETE;

    // Precompute all CLA-applied HRPWM values
    precomputePhaseShiftPeriodsForCLA();

    // Override SysConfig default software trigger: Task1 runs from EPWM1INT
    CLA_setTriggerSource(CLA_TASK_1, CLA_TRIGGER_EPWM1INT);

    // Calling SFO() updates the HRMSTEP register with calibrated MEP_ScaleFactor.
    // HRMSTEP must be populated with a scale factor value prior to enabling
    // high resolution period control.
    while(status == SFO_INCOMPLETE)
    {
        status = SFO();
        if(status == SFO_ERROR)
        {
            error();   // SFO function returns 2 if an error occurs & # of MEP
        }              // steps/coarse step exceeds maximum of 255.
    }



    // Disable sync(Freeze clock to PWM as well)
    SysCtl_disablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);
    SysCtl_setEPWMClockDivider(SYSCTL_EPWMCLK_DIV_1);

    initHRPWM1(ePWM[1], EPWM_TIMER_TBPRD);

    // Enable sync and clock to PWM
    SysCtl_enablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);

    // Arm external lead/lag commands only after PWM is fully configured.
    configureLagLeadHardwareTriggers();
    cla_cmd_direction = PHASE_NONE;
    cla_cmd_cycles = 0U;
    cla_cmd_seq = 0U;
    cla_state_direction = PHASE_NONE;
    cla_state_cycles_remaining = 0U;
    cla_state_active = 0U;
    cla_cmd_ack_seq = cla_cmd_seq;
    cla_done_count = 0U;


    // Enable ePWM interrupts
    //Interrupt_enable(INT_EPWM1);
    //Interrupt_enable(INT_EPWM2);
    //Interrupt_enable(INT_EPWM3);
    //Interrupt_enable(INT_EPWM4);

    // Enable Global Interrupt (INTM) and realtime interrupt (DBGM)
    EINT;
    ERTM;

    for(;;)
    {
        //DEVICE_DELAY_US(1000);
            
        //float32_t count = (dutyFine * (float32_t)(EPWM_TIMER_TBPRD << 8))/100;
        //uint32_t compCount = (count);
        // only set compare A for duty cycle change, B set autoamtically by deadband
        // will need to move this to init function
        
        //
        // Call the scale factor optimizer lib function SFO()
        // periodically to track for any change due to temp/voltage.
        // This function generates MEP_ScaleFactor by running the
        // MEP calibration module in the HRPWM logic. This scale
        // factor can be used for all HRPWM channels. The SFO()
        // function also updates the HRMSTEP register with the
        // scale factor value.
        //
        status = SFO(); // in background, MEP calibration module
                        // continuously updates MEP_ScaleFactor

        if (status == SFO_ERROR)
        {
            error();   // SFO function returns 2 if an error occurs & #
                    // of MEP steps/coarse step
        }              // exceeds maximum of 255.
     }
}

void initHRPWM1(uint32_t base, uint32_t period)
{

    //
    // ePWM channel register configuration with HRPWM
    // ePWMxA / ePWMxB toggle low/high with MEP control on Rising edge
    //
    
    EPWM_setEmulationMode(base, EPWM_EMULATION_FREE_RUN);

    // Set-up TBCLK
    EPWM_setTimeBasePeriod(base, period-1U);
    HRPWM_setTimeBasePeriod(base, ((period-1U) << 8));
    EPWM_setPhaseShift(base, 0U);
    EPWM_setTimeBaseCounter(base, 0U);
    EPWM_setTimeBaseCounterMode(base, EPWM_COUNTER_MODE_UP);
    EPWM_setClockPrescaler(base,
                            EPWM_CLOCK_DIVIDER_1,
                            EPWM_HSCLOCK_DIVIDER_1);
    //EPWM_disablePhaseShiftLoad(base);

    // Sync-out generation from this channel:
    // Generates EPWMxSYNCO pulse at TBCTR = ZERO once per PWM cycle.
    EPWM_setSyncOutPulseMode(base, EPWM_SYNC_OUT_PULSE_ON_COUNTER_ZERO);
    // set duty 50% initially
    HRPWM_setCounterCompareValue(base, HRPWM_COUNTER_COMPARE_A, (period/2 << 8));
    HRPWM_setChannelBOutputPath(base, HRPWM_OUTPUT_ON_B_NORMAL);
    // Set up shadowing
    EPWM_setCounterCompareShadowLoadMode(base,
                                            EPWM_COUNTER_COMPARE_A,
                                            EPWM_COMP_LOAD_ON_CNTR_ZERO);
    
    // Set actions
    // AQ source waveform on A only:
    // A goes high at counter zero, low at up-count compare A.
    EPWM_setActionQualifierAction(base, EPWM_AQ_OUTPUT_A, EPWM_AQ_OUTPUT_HIGH, EPWM_AQ_OUTPUT_ON_TIMEBASE_ZERO);
    EPWM_setActionQualifierAction(base, EPWM_AQ_OUTPUT_A, EPWM_AQ_OUTPUT_LOW,  EPWM_AQ_OUTPUT_ON_TIMEBASE_UP_CMPA);

    // Keep B AQ neutral so deadband module owns B waveform generation.
    EPWM_setActionQualifierAction(base, EPWM_AQ_OUTPUT_B, EPWM_AQ_OUTPUT_NO_CHANGE, EPWM_AQ_OUTPUT_ON_TIMEBASE_ZERO);
    EPWM_setActionQualifierAction(base, EPWM_AQ_OUTPUT_B, EPWM_AQ_OUTPUT_NO_CHANGE, EPWM_AQ_OUTPUT_ON_TIMEBASE_UP_CMPB);

    // HR duty/period mode on channel A.
    // This mode supports both CMPAHR (duty edge) and TBPRDHR (period edge).
    HRPWM_setMEPEdgeSelect(base, HRPWM_CHANNEL_A, HRPWM_MEP_CTRL_FALLING_EDGE);
    HRPWM_setMEPControlMode(base, HRPWM_CHANNEL_A, HRPWM_MEP_DUTY_PERIOD_CTRL);
    HRPWM_setCounterCompareShadowLoadEvent(base, HRPWM_CHANNEL_A, HRPWM_LOAD_ON_CNTR_ZERO);

    // Required for MEP scaling conversion.
    HRPWM_enableAutoConversion(base);
    HRPWM_enablePeriodControl(base);

    // Deadband path setup to create Active-High Complementary output:
    // RED and FED both enabled, both sourced from EPWMA.
    HRPWM_setDeadBandDelayMode(base, EPWM_DB_RED, true);
    HRPWM_setDeadBandDelayMode(base, EPWM_DB_FED, true);
    HRPWM_setRisingEdgeDeadBandDelayInput(base, EPWM_DB_INPUT_EPWMA);
    HRPWM_setFallingEdgeDeadBandDelayInput(base, EPWM_DB_INPUT_EPWMA);

    // Active-High Complementary polarity:
    // RED not inverted, FED inverted.
    HRPWM_setDeadBandDelayPolarity(base, EPWM_DB_RED, EPWM_DB_POLARITY_ACTIVE_HIGH);
    HRPWM_setDeadBandDelayPolarity(base, EPWM_DB_FED, EPWM_DB_POLARITY_ACTIVE_LOW);

    // Deadband counter clock mode.
    EPWM_setDeadBandCounterClock(base, EPWM_DB_COUNTER_CLOCK_FULL_CYCLE);

    // High-resolution deadband load modes and initial values.
    HRPWM_setRisingEdgeDelayLoadMode(base, HRPWM_LOAD_ON_CNTR_ZERO);
    HRPWM_setFallingEdgeDelayLoadMode(base, HRPWM_LOAD_ON_CNTR_ZERO);
    HRPWM_setRisingEdgeDelay(base, DB_RED_HR_COUNT);
    HRPWM_setFallingEdgeDelay(base, DB_FED_HR_COUNT);

    EPWM_setInterruptSource(base, EPWM_INT_TBCTR_ZERO);
    EPWM_setInterruptEventCount(base, 1U);
    EPWM_clearEventTriggerInterruptFlag(base);
    EPWM_enableInterrupt(base);
}

static void precomputePhaseShiftPeriodsForCLA(void)
{
    // Keep this consistent with your current TBPRD usage.
    // You currently write TBPRD with period-1, so use (EPWM_TIMER_TBPRD - 1U).
    const float32_t cN  = (float32_t)(EPWM_TIMER_TBPRD - 1U);
    const float32_t den = (float32_t)PHASE_DEN;

    // fL/fH equivalent in count domain
    const float32_t cL = cN * ((den + 1.0f) / den);   // slower (lag)
    const float32_t cH = cN * ((den - 1.0f) / den);   // faster (lead)

    // Convert to Q8 consolidated format for TBPRDHR/CMPA writes
    cla_period_hr_normal_q8 = (uint32_t)(cN * 256.0f);
    cla_period_hr_slow_q8   = (uint32_t)(cL * 256.0f);
    cla_period_hr_fast_q8   = (uint32_t)(cH * 256.0f);

    // Keep 50% duty through frequency excursion
    cla_cmpa_hr_normal_q8 = cla_period_hr_normal_q8 >> 1U;
    cla_cmpa_hr_slow_q8   = cla_period_hr_slow_q8 >> 1U;
    cla_cmpa_hr_fast_q8   = cla_period_hr_fast_q8 >> 1U;
}

static void configureLagLeadHardwareTriggers(void)
{
    Interrupt_register(INT_XINT1, &xintLeadIsr);
    Interrupt_register(INT_XINT2, &xintLagIsr);

    GPIO_setDirectionMode(16U, GPIO_DIR_MODE_IN);
    GPIO_setDirectionMode(24U, GPIO_DIR_MODE_IN);
    GPIO_setPadConfig(16U, GPIO_PIN_TYPE_PULLUP);
    GPIO_setPadConfig(24U, GPIO_PIN_TYPE_PULLUP);
    GPIO_setQualificationMode(16U, GPIO_QUAL_6SAMPLE);
    GPIO_setQualificationMode(24U, GPIO_QUAL_6SAMPLE);

    GPIO_setInterruptPin(16U, GPIO_INT_XINT1); // lead command
    GPIO_setInterruptType(GPIO_INT_XINT1, GPIO_INT_TYPE_RISING_EDGE);
    GPIO_enableInterrupt(GPIO_INT_XINT1);

    GPIO_setInterruptPin(24U, GPIO_INT_XINT2); // lag command
    GPIO_setInterruptType(GPIO_INT_XINT2, GPIO_INT_TYPE_RISING_EDGE);
    GPIO_enableInterrupt(GPIO_INT_XINT2);

    Interrupt_enable(INT_XINT1);
    Interrupt_enable(INT_XINT2);
}

__interrupt void xintLeadIsr(void)
{
    xint1_hits++;
    if(cla_state_active == 0U)
    {
        cla_cmd_direction = PHASE_LEAD;
        cla_cmd_cycles    = N_PHASE_CYCLES;
        cla_cmd_seq++;
    }

    Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP1);
}

__interrupt void xintLagIsr(void)
{
    xint2_hits++;
    if(cla_state_active == 0U)
    {
        cla_cmd_direction = PHASE_LAG;
        cla_cmd_cycles    = N_PHASE_CYCLES;
        cla_cmd_seq++;
    }

    Interrupt_clearACKGroup(INTERRUPT_ACK_GROUP1);
}

//
// error - Halt debugger when called
//
void error (void)
{
    ESTOP0;         // Stop here and handle error
}

